# Generated by Django 4.1 on 2022-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fupload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='upload_file',
        ),
    ]
