# Generated by Django 4.1 on 2022-08-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_upload_delete_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='fupload',
            new_name='file',
        ),
    ]
