# Generated by Django 4.1 on 2022-08-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fupload_upload_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='uploads',
        ),
    ]
