# Generated by Django 4.1 on 2022-08-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_upload_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploads',
        ),
    ]
