# Generated by Django 4.1 on 2022-08-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_delete_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='tosave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=50)),
                ('field_2', models.CharField(max_length=50)),
                ('field_3', models.CharField(max_length=200)),
                ('field_4', models.CharField(max_length=200)),
                ('field_5', models.CharField(max_length=200)),
                ('field_6', models.CharField(max_length=200)),
                ('field_7', models.CharField(max_length=200)),
                ('field_8', models.CharField(max_length=200)),
                ('field_9', models.CharField(max_length=200)),
                ('field_10', models.CharField(max_length=200)),
                ('field_11', models.CharField(max_length=200)),
                ('field_12', models.CharField(max_length=200)),
            ],
        ),
    ]
